---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - curator.operatefirst.io
  resources:
  - curatorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - curator.operatefirst.io
  resources:
  - curatorconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - curator.operatefirst.io
  resources:
  - curatorconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - curator.operatefirst.io
  resources:
  - reports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - curator.operatefirst.io
  resources:
  - reports/finalizers
  verbs:
  - update
- apiGroups:
  - curator.operatefirst.io
  resources:
  - reports/status
  verbs:
  - get
  - patch
  - update
