apiVersion: curator.operatefirst.io/v1alpha1
kind: FetchData
metadata:
  name: fetchdata-sample
spec:
  cronjobNamespace: koku-metrics-operator
  schedule: "0 */6 * * *"  # This job will run every 6 hours. You can also use " schedule: '* * * * *' " to run this cron job instantly
  backupSrc: /tmp/koku-metrics-operator-data/upload
  unzipDir: /tmp/koku-metrics-operator-data/s3sync
  databaseName: <database-name>
  databasePassword: <password>
  databaseUser: <user-name>
  databaseHostName: <hostname or host ip>
  databasePort: <port-number>
  has_s3_access: <true if you want to save files in s3 bucket else, false>
  aws_access_key_id: <if has_s3_access variable is true provide the credentials, else nil>
  aws_secret_access_key: <if has_s3_access variable is true provide the credentials, else nil>
  bucket_name: <if has_s3_access variable is true provide the S3 bucket name, else nil>
  s3_host_name: <if has_s3_access variable is true provide the hostname, else nil>
