apiVersion: curator.operatefirst.io/v1alpha1
kind: Report
metadata:
  name: day-report
spec:
  cronjobNamespace: koku-metrics-operator
  # scheduleForReport: "*/5 * * * *"
  databaseName: <database-name>
  databasePassword: <password>
  databaseUser: <user-name>
  databaseHostName: <hostname or host ip>
  databasePort: <port-number>
  reportFrequency: <day,week or month>
