name: ci
on:
  pull_request:
    branches:
    - main
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: ~1.17
      id: go

    - name: Cache the go module cache
      id: cache-go-mod
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: go mod download

    - name: Run verification checks
      run: make verify

    - name: Run unit tests
      run: make test

    - name: Verify controller binary can compile
      run: make build

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run linting checks
      uses: "golangci/golangci-lint-action@v2"
      with:
        version: "v1.43"

  olm-bundle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: ~1.17

    # TODO(tflannag): cache this installation?
    # TODO(tflannag): Create an operator-sdk github action?
    - name: Download operator sdk
      shell: bash
      env:
        RELEASE_VERSION: v1.17.0
      run: |
        curl --output operator-sdk -JL https://github.com/operator-framework/operator-sdk/releases/download/$RELEASE_VERSION/operator-sdk_linux_amd64
        chmod +x operator-sdk
        sudo mv operator-sdk /usr/local/bin

    - name: Verify manifests are up-to-date
      run: make bundle && make diff
